client_config_backend: settings
client_config:
  client_id: "634445818150-ki958a4ca0ste7mjsb11en8cg88lagfi.apps.googleusercontent.com"
  client_secret: "GT54DsBdU9Ze_WHqu_3L0xsv"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
  - https://www.googleapis.com/auth/drive